import pandas as pd
from agent import retrieve_historical_examples, client

results = pd.read_csv("agent_results.csv")

print("Agent results loaded successfully.")
print("Number of replies:", len(results))

print("\nColumns:")
print(results.columns.tolist())

print("\nSaved examples:")
print(results[["customer_text", "actual_intent", "predicted_intent"]])

judge_results = results.iloc[1:4].copy()

print("\nReplies selected for LLM-as-judge:")
print(len(judge_results))

def build_judge_prompt(row):
    historical_examples = retrieve_historical_examples(
        row["customer_text"],
        top_k=3
    )

    historical_context = ""

    for _, example in historical_examples.iterrows():
        historical_context += (
            f"Customer: {example['customer_text']}\n"
            f"Support reply: {example['spotify_reply']}\n\n"
        )

    prompt = f"""
You are evaluating a customer-support reply generated by an AI agent.

Customer message:
{row["customer_text"]}

AI-generated reply:
{row["draft_reply"]}

Predicted intent:
{row["predicted_intent"]}

Predicted action:
{row["predicted_action"]}

Historical support examples:
{historical_context}

Evaluate the reply using these four criteria.

1. Historical grounding:
Does the reply stay consistent with the historical support examples?

2. Relevance/helpfulness:
Does the reply appropriately address the customer's message?

3. No unsupported claims:
Does the reply avoid inventing account information, claiming actions were performed,
or making unsupported promises?

4. Escalation handling:
Is the response appropriate given the predicted action
(Auto-handle or Escalate)?

Give each criterion a score from 0 to 2.

Return exactly these five lines:

Historical grounding: <0, 1, or 2>
Relevance/helpfulness: <0, 1, or 2>
No unsupported claims: <0, 1, or 2>
Escalation handling: <0, 1, or 2>
Reason: <short explanation>
"""

    return prompt

judge_outputs = []

for _, row in judge_results.iterrows():

    try:
        response = client.models.generate_content(
            model="gemini-3.6-flash",
            contents=build_judge_prompt(row)
        )
    except Exception as e:
        print("\nJudge call failed:")
        print(e)
        continue

    judge_text = response.text.strip()

    print("\nJudge response:")
    print(judge_text)

    judge_scores = {
        "customer_text": row["customer_text"],
        "historical_grounding": None,
        "relevance_helpfulness": None,
        "no_unsupported_claims": None,
        "escalation_handling": None,
        "reason": ""
    }

    for line in judge_text.splitlines():

        if line.startswith("Historical grounding:"):
            judge_scores["historical_grounding"] = int(
                line.split(":", 1)[1].strip()
            )

        elif line.startswith("Relevance/helpfulness:"):
            judge_scores["relevance_helpfulness"] = int(
                line.split(":", 1)[1].strip()
            )

        elif line.startswith("No unsupported claims:"):
            judge_scores["no_unsupported_claims"] = int(
                line.split(":", 1)[1].strip()
            )

        elif line.startswith("Escalation handling:"):
            judge_scores["escalation_handling"] = int(
                line.split(":", 1)[1].strip()
            )

        elif line.startswith("Reason:"):
            judge_scores["reason"] = line.split(":", 1)[1].strip()

    judge_scores["total_score"] = (
        judge_scores["historical_grounding"]
        + judge_scores["relevance_helpfulness"]
        + judge_scores["no_unsupported_claims"]
        + judge_scores["escalation_handling"]
    )

    judge_outputs.append(judge_scores)


judge_df = pd.DataFrame(judge_outputs)

judge_df.to_csv(
    "llm_judge_results.csv",
    mode="a",
    header=not __import__("os").path.exists("llm_judge_results.csv"),
    index=False
)

print("\nLLM judge results saved successfully.")
print("Number of judged replies:", len(judge_df))

all_judge_results = pd.read_csv("llm_judge_results.csv")

print("\nTotal judged replies:")
print(len(all_judge_results))

average_score = all_judge_results["total_score"].mean()
percentage_score = (average_score / 8) * 100

print("\nAverage judge score:")
print(f"{average_score:.2f}/8")

print("\nAverage judge score percentage:")
print(f"{percentage_score:.2f}%")